src/objects/Baby_Activity__c.object
<CustomObject>
    <description>Used for tracking baby stuff</description>
    <fields>
        <fullName>Amount_ML__c</fullName>
        <label>Amount (ML)</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Amount_OZ__c</fullName>
        <formula>Amount_ML__c /30</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Amount (OZ)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Amount__c</fullName>
        <description>Returns Feed Amount or Hours Slept based on record type of the record</description>
        <formula>CASE( RecordType.DeveloperName , 
&apos;Feed&apos;,  TEXT(Amount_ML__c) &amp; &apos; (ml)&apos;, 
&apos;Sleep&apos;,  IF(!ISBLANK( Sleep_End_Datetime__c ), TEXT(Hours_Slept__c) &amp; &apos; hours&apos;, &apos;In progress...&apos;) , 
&apos;Play&apos;,  IF(!ISBLANK( Sleep_End_Datetime__c ), TEXT(Hours_Slept__c) &amp; &apos; hours&apos;, &apos;In progress...&apos;) , 
&apos;&apos;)</formula>
        <inlineHelpText>Returns Feed Amount or Hours Slept based on record type of the record</inlineHelpText>
        <label>Amount</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Comments__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Comments</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Date_Time__c</fullName>
        <defaultValue>NOW()</defaultValue>
        <encryptionScheme>None</encryptionScheme>
        <label>Start Date / Time</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <formula>DATEVALUE(TEXT( Date_Time__c - 4/24) )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Food_Type__c</fullName>
        <label>Food Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Breastmilk</fullName>
                    <default>true</default>
                    <label>Breastmilk</label>
                </value>
                <value>
                    <fullName>Formula</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Hours_Slept__c</fullName>
        <formula>ROUND((Sleep_End_Datetime__c - Date_Time__c)*24,2)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Hours Slept</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Icon__c</fullName>
        <formula>CASE( RecordType.DeveloperName , 
&apos;Sleep&apos;,&apos;💤&apos;, 
&apos;Feed&apos;, &apos;🐽&apos;,
&apos;Play&apos;, &apos;️⚽️&apos;,
&apos;Heal&apos;, &apos;💉&apos;,
&apos;💨&apos;)</formula>
        <label>Icon</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Medicine_Amount__c</fullName>
        <label>Medicine Amount</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Medicine_Units__c</fullName>
        <inlineHelpText>Unit of measure for meds</inlineHelpText>
        <label>Medicine Units</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>ML</fullName>
                </value>
                <value>
                    <fullName>IU</fullName>
                </value>
                <value>
                    <fullName>OZ</fullName>
                </value>
                <value>
                    <fullName>Pill</fullName>
                </value>
                <value>
                    <fullName>Dose</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Medicine__c</fullName>
        <label>Medicine</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Tylenol</fullName>
                </value>
                <value>
                    <fullName>Eye Drops</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sleep_End_Datetime__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>End Date / Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Time__c</fullName>
        <formula>TIMEVALUE(Date_Time__c - 4/24)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Time</label>
        <type>Time</type>
    </fields>
    <fields>
        <fullName>Vitamin_D_Drops__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Vitamin D Drops</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Vitamin_D_IU__c</fullName>
        <description>Calculates the amount of Vitamin D IUs per feed</description>
        <formula>IF(  ISPICKVAL(Food_Type__c, &apos;Breastmilk&apos;)   , 
 Vitamin_D_Drops__c *  $Setup.CT_Defaults__c.Vitamin_D_per_Drop__c 
,  Amount_ML__c *  $Setup.CT_Defaults__c.Vitamin_D_Per_Formula__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Vitamin D IU</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Baby Activity</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>Activity Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Baby Activities</pluralLabel>
    <recordTypes>
        <fullName>Feed</fullName>
        <active>true</active>
        <label>Feed</label>
    </recordTypes>
    <recordTypes>
        <fullName>Heal</fullName>
        <active>true</active>
        <label>Heal</label>
    </recordTypes>
    <recordTypes>
        <fullName>Play</fullName>
        <active>true</active>
        <label>Play</label>
    </recordTypes>
    <recordTypes>
        <fullName>Sleep</fullName>
        <active>true</active>
        <label>Sleep</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CT_Defaults__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Cole Tracker Defaults</label>
</CustomObject>

src/classes/ApexHelperController.cls
/**
 * Created by gmt on 6/13/2019.
 */

public with sharing class ApexHelperController {

    @AuraEnabled//(Cacheable=true)
    public static Baby_Activity__c getLastFeed(){

        LIST<Baby_Activity__c> acts = [SELECT Id,
                Date_Time__c,
                Amount_ML__c,
                Amount_OZ__c,
                Vitamin_D_Drops__c,
                Food_Type__c,
                Time__c,
                Icon__c,
                Amount__c
                FROM Baby_Activity__c
                WHERE RecordType.DeveloperName = 'Feed'
                ORDER BY Date_Time__c DESC
                LIMIT 1 ];

        return acts.size() > 0 ? acts[0] : null;

    }

    @AuraEnabled//(Cacheable=true)
    public static Baby_Activity__c getLastSleep(){

        LIST<Baby_Activity__c> acts = [SELECT Id,
                Date_Time__c,
                Sleep_End_Datetime__c,
                Hours_Slept__c,
                Icon__c,
                Amount__c
        FROM Baby_Activity__c
        WHERE RecordType.DeveloperName = 'Sleep'
        ORDER BY Date_Time__c DESC
        LIMIT 1 ];

        return acts.size() > 0 ? acts[0] : null;

    }

    @AuraEnabled//(Cacheable=true)
    public static Baby_Activity__c getLastCompletedSleep(){

        LIST<Baby_Activity__c> acts = [SELECT Id,
                Date_Time__c,
                Sleep_End_Datetime__c,
                Hours_Slept__c,
                Icon__c,
                Amount__c
        FROM Baby_Activity__c
        WHERE RecordType.DeveloperName = 'Sleep'
        AND Sleep_End_Datetime__c != null
        ORDER BY Date_Time__c DESC
        LIMIT 1 ];

        return acts.size() > 0 ? acts[0] : null;

    }


    @AuraEnabled //(Cacheable=true)
    public static Baby_Activity__c getLastHeal(){

        LIST<Baby_Activity__c> acts = [SELECT Id,
                Date_Time__c,
                Medicine__c,
                Medicine_Amount__c,
                Medicine_Units__c,
                Comments__c,
                Time__c,
                Icon__c
        FROM Baby_Activity__c
        WHERE RecordType.DeveloperName = 'Heal'
        ORDER BY Date_Time__c DESC
        LIMIT 1 ];

        return acts.size() > 0 ? acts[0] : null;

    }

    @AuraEnabled//(Cacheable=true)
    public static Baby_Activity__c getLastPlay(){

        LIST<Baby_Activity__c> acts = [SELECT Id,
                Name,
                Date_Time__c,
                Sleep_End_Datetime__c,
                Icon__c,
                Amount__c,
                Comments__c,
                RecordType.Name,
                RecordTypeId
        FROM Baby_Activity__c
        WHERE RecordType.DeveloperName = 'Play'
        ORDER BY Date_Time__c DESC
        LIMIT 1 ];

        return acts.size() > 0 ? acts[0] : null;

    }

    @AuraEnabled(Cacheable=true)
    public static Integer getTotalVitaminDToday(){

        LIST<Baby_Activity__c> acts = [SELECT Id,
                Date_Time__c,
                Vitamin_D_IU__c,
                Icon__c
                FROM Baby_Activity__c
                WHERE RecordType.Name = 'Feed'
                AND Date__c = TODAY
        ];
        integer total = 0;
        for(Baby_Activity__c item : acts){
            total += Integer.valueOf(item.Vitamin_D_IU__c);
        }
        return total;
    }

    @AuraEnabled//(Cacheable=true)
    public static decimal getTotalSleepToday(){

        LIST<Baby_Activity__c> acts = [SELECT Id,
                Date_Time__c,
                Sleep_End_Datetime__c,
                Date__c,
                Time__c,
                Hours_Slept__c,
                Icon__c
        FROM Baby_Activity__c
        WHERE RecordType.DeveloperName = 'Sleep'
        AND Sleep_End_Datetime__c = TODAY
        ];
        decimal total = 0;
        for(Baby_Activity__c item : acts){
            total += item.Hours_Slept__c;
        }
        return total;
    }

    @AuraEnabled//(Cacheable=true)
    public static Integer getTotalFoodMLToday(){

        LIST<Baby_Activity__c> acts = [SELECT Id,
                Date_Time__c,
                Amount_ML__c,
                Icon__c
        FROM Baby_Activity__c
        WHERE RecordType.DeveloperName = 'Feed'
        AND Date_Time__c = TODAY
        ];
        integer totalML = 0;
        for(Baby_Activity__c item : acts){
            totalML += Integer.valueOf(item.Amount_ML__c);
        }
        return totalML;
    }

    @AuraEnabled(Cacheable=true)
    public static BabyPayload getAverageFoodPerDay(){
        LIST<AggregateResult> acts = [SELECT Date__c,
                SUM(Amount_ML__c)
                FROM Baby_Activity__c
                WHERE RecordType.DeveloperName = 'Feed'
                AND Date_Time__c = LAST_N_DAYS:7
                AND Date_Time__c < TODAY
                GROUP BY Date__c
        ];
        integer totalML = 0;
        for(AggregateResult item : acts){
            system.debug(item);
            totalML += Integer.valueOf(item.get('expr0'));
        }
        Integer numberOfRecords = acts.size();
        Double avg = totalML / numberOfRecords;

        BabyPayload payload = new BabyPayload();
        payload.AverageDays = numberOfRecords;
        payload.AverageAmountPerDay = avg;
        return payload;
    }

    @AuraEnabled(Cacheable=true)
    public static BabyPayload getAverageSleepPerDay(){
        LIST<AggregateResult> acts = [SELECT Date__c,
                SUM(Hours_Slept__c)
        FROM Baby_Activity__c
        WHERE RecordType.DeveloperName = 'Sleep'
        AND Date_Time__c = LAST_N_DAYS:7
        AND Date_Time__c < TODAY
        GROUP BY Date__c
        ];
        integer totalML = 0;
        for(AggregateResult item : acts){
            system.debug(item);
            totalML += Integer.valueOf(item.get('expr0'));
        }
        Integer numberOfRecords = acts.size();
        Double avg = totalML / numberOfRecords;

        BabyPayload payload = new BabyPayload();
        payload.AverageDays = numberOfRecords;
        payload.AverageAmountPerDay = avg;
        return payload;
    }


    @AuraEnabled(Cacheable=true)
    public static CT_Defaults__c getDefaults(){
        return CT_Defaults__c.getOrgDefaults();
    }


    @AuraEnabled(Cacheable=true)
    public static Id getRecordTypeIdForName(String devName){
        return AuraDataWriter.getRecordTypeIdForName(devName);
    }

    @AuraEnabled
    public static Baby_Activity__c updateSleepRecord(Id recordId, Datetime endDate){
        AuraDataWriter.updateSleepRecord(recordId,endDate);
        return getLastSleep();
    }
}