src/objects/Baby_Activity__c.object
<CustomObject>
    <description>Used for tracking baby stuff</description>
    <fields>
        <fullName>Comments__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Comments</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Date_Time__c</fullName>
        <defaultValue>NOW()</defaultValue>
        <encryptionScheme>None</encryptionScheme>
        <label>Start Date / Time</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Icon__c</fullName>
        <formula>CASE( RecordType.DeveloperName , 
&apos;Sleep&apos;,&apos;💤&apos;, 
&apos;Feed&apos;, &apos;🐽&apos;,
&apos;Play&apos;, &apos;️⚽️&apos;,
&apos;Heal&apos;, &apos;💉&apos;,
&apos;💨&apos;)</formula>
        <label>Icon</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sleep_End_Datetime__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>End Date / Time</label>
        <type>DateTime</type>
    </fields>
    <label>Baby Activity</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>Activity Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Baby Activities</pluralLabel>
    <recordTypes>
        <fullName>Play</fullName>
        <active>true</active>
        <label>Play</label>
    </recordTypes>
    <recordTypes>
        <fullName>Sleep</fullName>
        <active>true</active>
        <label>Sleep</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/AuraDataWriter.cls
/**
 * Created by gmt on 2019-06-27.
 */

public with sharing class AuraDataWriter {

    @AuraEnabled
    public static Baby_Activity__c savePlayRecord(Datetime startTime, Datetime endTime, String comments, Id recordId){
        Baby_Activity__c record = new Baby_Activity__c();
        record.Date_Time__c = startTime;
        record.RecordTypeId = getRecordTypeIdForName('Play');
        record.Sleep_End_Datetime__c = endTime;
        record.Comments__c = comments;
        if(recordId != null){
            record.Id = recordId;
        }
        upsert record;
        record = [SELECT Id, Name, Date_Time__c, RecordTypeId, Sleep_End_Datetime__c, Comments__c, Icon__c FROM Baby_Activity__c WHERE Id =: record.Id LIMIT 1];
        return record;
    }

    @AuraEnabled
    public static void updateSleepRecord(Id recordId, Datetime endDate){
        if(recordId != null){
            Baby_Activity__c rec = new Baby_Activity__c(Id = recordId, Sleep_End_Datetime__c = endDate);
            System.debug(rec);
            update rec;
        } else {
            throw new saveException('No record ID was provided');
        }
    }

    @AuraEnabled
    public static void startNewSleepRecord(Datetime startTime){

        List<Id> active = BabyTriggerHelper.getActiveSleepIds();
        if(active.size() > 0){
            throw new saveException('An active sleep record already exists: ' + String.join(active,','));
        }

        if(startTime == null){
            startTime = System.now();
        }
        Baby_Activity__c rec = new Baby_Activity__c(Date_Time__c = startTime, RecordTypeId =getRecordTypeIdForName('Sleep'));

        insert rec;
    }

    @AuraEnabled
    public static void deleteRecord(Id recordId){
        if(recordId == null){
            throw new deleteException('No record ID was provided');
        }
        delete [SELECT Id FROM Baby_Activity__c WHERE Id =: recordId LIMIT 1];
    }


    @AuraEnabled(Cacheable=true)
    public static Id getRecordTypeIdForName(String devName){
        return getMapOfRecordTypes().get(devName.toLowerCase());
    }


    @AuraEnabled(Cacheable=true)
    public static Map<String, Id> getMapOfRecordTypes(){

        Map<String, Id> rtMap = new Map<String, Id>();
        Schema.SObjectType  objType = Baby_Activity__c.SObjectType;
        for(RecordTypeInfo rt : objType.getDescribe().getRecordTypeInfos()){
            rtMap.put(rt.getDeveloperName().toLowerCase(),rt.getRecordTypeId());
        }
        return rtMap;
    }

    public class deleteException extends Exception{

    }
    public class saveException extends Exception{

    }
}