src/objects/Baby_Activity__c.object
<CustomObject>
    <description>Used for tracking baby stuff</description>
    <fields>
        <fullName>Baby__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Baby</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Baby Activities</relationshipLabel>
        <relationshipName>Baby_Activities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Comments__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Comments</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Date_Time__c</fullName>
        <defaultValue>NOW()</defaultValue>
        <encryptionScheme>None</encryptionScheme>
        <label>Start Date / Time</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <formula>DATEVALUE(TEXT( Date_Time__c - 4/24) )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Hours_Slept__c</fullName>
        <formula>ROUND((Sleep_End_Datetime__c - Date_Time__c)*24,2)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Hours Slept</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Icon__c</fullName>
        <formula>CASE( RecordType.DeveloperName , 
&apos;Sleep&apos;,&apos;💤&apos;, 
&apos;Feed&apos;, &apos;🐽&apos;,
&apos;Play&apos;, &apos;️⚽️&apos;,
&apos;Heal&apos;, &apos;💉&apos;,
&apos;💨&apos;)</formula>
        <label>Icon</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sleep_End_Datetime__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>End Date / Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Time__c</fullName>
        <formula>TIMEVALUE(Date_Time__c - 4/24)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Time</label>
        <type>Time</type>
    </fields>
    <label>Baby Activity</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>Activity Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Baby Activities</pluralLabel>
    <recordTypes>
        <fullName>Feed</fullName>
        <active>true</active>
        <label>Feed</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ActivityTimeline_Controller.cls
public class ActivityTimeline_Controller {

    @AuraEnabled
    public static List<ActivityTimeline_Model> getActivityTimeline()
    {
        // Create a return List
        List<ActivityTimeline_Model> returnList = new List<ActivityTimeline_Model>();

            // Add Tasks Types
            addFeeds(returnList);
            //addCalls(returnList, recordId);
            //addMeetings(returnList, recordId);
            //addEmails(returnList, recordId);
            // Sort List
            //returnList.sort();


        return returnList;

    }

    @AuraEnabled
    public static void addFeeds(List<ActivityTimeline_Model> returnList)
    {
        //List<Task> taskList =[select   Id, Type, Owner.Name, Status, Who.Name, Subject, Description, ActivityDate from     Task where    WhatId =:recordId and (Type = 'Other' OR Type = Null) and ActivityDate != null ];
        LIST<Baby_Activity__c> recs = [SELECT Id,
                Date_Time__c,
                Date__c,
                Time__c,
                Hours_Slept__c,
                Sleep_End_Datetime__c,
                Icon__c,
                RecordType.Name,
                Comments__c,
                Owner.Name,
                Baby__r.Name
                FROM Baby_Activity__c
                //WHERE RecordType.DeveloperName = 'Feed'
                WHERE Date_Time__c >= YESTERDAY
                ORDER BY Date_Time__c DESC
            ];
        for(Baby_Activity__c t: recs)
        {
            ActivityTimeline_Model taskItem = new ActivityTimeline_Model();

            taskItem.RecordId = t.Id;
            taskItem.ActivityTimelineType = 'Feed';
            taskItem.Subject = t.RecordType.Name;//t.Subject;
            taskItem.Detail = t.Comments__c;
            taskItem.ActualDate = t.Date_Time__c;
            taskItem.ShortDate = t.Date_Time__c.format();
            taskItem.Recipients = t.Baby__r.Name;
            taskItem.Assigned = t.Owner.Name;
            taskItem.Icon = t.Icon__c;

            returnList.add(taskItem);
        }
    }


}